const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3003";

export const ENDPOINTS = {
  STUDENT: {
    LOGIN: `${API_BASE_URL}/auth/student/login`,
    REGISTER: `${API_BASE_URL}/auth/student/register`,
    PROFILE: `${API_BASE_URL}/students/profile`,
    REGISTER_FYP: `${API_BASE_URL}/students/register-fyp`,
    DEPARTMENTS: `${API_BASE_URL}/students/departments`,
    SEARCH: `${API_BASE_URL}/auth/student/search`,
    ANNOUNCEMENTS: `${API_BASE_URL}/student/announcements`,
  },
  SUPERVISOR: {
    LOGIN: `${API_BASE_URL}/auth/supervisor/login`,
    PROFILE: `${API_BASE_URL}/auth/supervisor/profile`,
    SET_PASSWORD: `${API_BASE_URL}/auth/supervisor/set-password`,
    UPDATE_PROFILE: `${API_BASE_URL}/auth/supervisor/profile`,
    UPDATE_PASSWORD: `${API_BASE_URL}/auth/supervisor/set-password`,
    DASHBOARD: `${API_BASE_URL}/dashboard/supervisor`,
    ASSIGNED_GROUPS: `${API_BASE_URL}/supervisor/assigned-groups`,
    ASSIGNED_GROUP_BY_ID: (groupId: string) => `${API_BASE_URL}/supervisor/assigned-groups/${groupId}`,
    CUSTOM_IDEAS: `${API_BASE_URL}/supervisor/custom-ideas`,
    CUSTOM_IDEA_APPROVE: (ideaId: string) => `${API_BASE_URL}/supervisor/custom-ideas/${ideaId}/approve`,
    CUSTOM_IDEA_REJECT: (ideaId: string) => `${API_BASE_URL}/supervisor/custom-ideas/${ideaId}/reject`,
    SELECTED_IDEAS: `${API_BASE_URL}/supervisor/selected-ideas`,
    SELECTED_IDEA_APPROVE: (ideaId: string) => `${API_BASE_URL}/supervisor/selected-ideas/${ideaId}/approve`,
    SELECTED_IDEA_REJECT: (ideaId: string) => `${API_BASE_URL}/supervisor/selected-ideas/${ideaId}/reject`,
    PROJECT_IDEAS: `${API_BASE_URL}/supervisor/project-ideas`,
    PROJECT_IDEA_BY_ID: (ideaId: string) => `${API_BASE_URL}/supervisor/project-ideas/${ideaId}`,
    PROPOSALS: `${API_BASE_URL}/supervisor/proposals`,
    PROPOSAL_BY_ID: (proposalId: string) => `${API_BASE_URL}/supervisor/proposals/${proposalId}`,
    PROPOSAL_APPROVE: (proposalId: string) => `${API_BASE_URL}/supervisor/proposals/${proposalId}/approve`,
    PROPOSAL_REJECT: (proposalId: string) => `${API_BASE_URL}/supervisor/proposals/${proposalId}/reject`,
    PROPOSAL_COMMENT: (proposalId: string) => `${API_BASE_URL}/supervisor/proposals/${proposalId}/comment`,
    DOCUMENTS: `${API_BASE_URL}/supervisor/documents`,
    DOCUMENT_DOWNLOAD: (documentId: string) => `${API_BASE_URL}/supervisor/documents/${documentId}/download`,
    DOCUMENT_APPROVE: (documentId: string) => `${API_BASE_URL}/supervisor/documents/${documentId}/approve`,
    DOCUMENT_REJECT: (documentId: string) => `${API_BASE_URL}/supervisor/documents/${documentId}/reject`,
    DOCUMENT_FEEDBACK: (documentId: string) => `${API_BASE_URL}/supervisor/documents/${documentId}/feedback`,
    FINAL_EVALUATIONS: `${API_BASE_URL}/supervisor/final-evaluations`,
    FINAL_EVALUATION_MARKS: (projectId: string) => `${API_BASE_URL}/supervisor/final-evaluations/${projectId}/marks`,
    FINAL_EVALUATION_FEEDBACK: (projectId: string) => `${API_BASE_URL}/supervisor/final-evaluations/${projectId}/feedback`,
    FINAL_EVALUATION_COMPLETE: (projectId: string) => `${API_BASE_URL}/supervisor/final-evaluations/${projectId}/complete`,
    MY_PANELS: `${API_BASE_URL}/supervisor/schedules/my-panels`,
    MY_PANEL_SCHEDULES: `${API_BASE_URL}/supervisor/schedules/panel-schedules`,
    ASSIGNED_GROUPS_SCHEDULES: `${API_BASE_URL}/supervisor/schedules/assigned-groups`,
    ANNOUNCEMENTS: `${API_BASE_URL}/supervisor/announcements`,
    ANNOUNCEMENT_BY_ID: (id: string) => `${API_BASE_URL}/supervisor/announcements/${id}`,
  },
  COORDINATOR: {
    LOGIN: `${API_BASE_URL}/auth/coordinator/login`,
    PROFILE: `${API_BASE_URL}/auth/coordinator/profile`,
    DASHBOARD: `${API_BASE_URL}/dashboard/coordinator`,
    TEACHERS: `${API_BASE_URL}/coordinator/teachers`,
    TEACHER_BY_ID: (teacherId: string) => `${API_BASE_URL}/coordinator/teachers/${teacherId}`,
    TEACHER_TRANSFER: (teacherId: string) => `${API_BASE_URL}/coordinator/teachers/${teacherId}/transfer`,
    TEACHER_AVAILABILITY: (teacherId: string) => `${API_BASE_URL}/coordinator/teachers/${teacherId}/availability`,
    ANNOUNCEMENTS: `${API_BASE_URL}/coordinator/announcements`,
    ANNOUNCEMENT_BY_ID: (id: string) => `${API_BASE_URL}/coordinator/announcements/${id}`,
  },
  DASHBOARD: {
    STUDENT: `${API_BASE_URL}/dashboard/student`,
    SUPERVISOR: `${API_BASE_URL}/dashboard/supervisor`,
    COORDINATOR: `${API_BASE_URL}/dashboard/coordinator`,
  },
  GROUP: {
    CREATE: `${API_BASE_URL}/groups`,
    MY_GROUP: `${API_BASE_URL}/groups/my-group`,
    ADD_MEMBER: (groupId: string) => `${API_BASE_URL}/groups/${groupId}/add-member`,
    REMOVE_MEMBER: (groupId: string, memberId: string) => `${API_BASE_URL}/groups/${groupId}/remove-member/${memberId}`,
    LEAVE: (groupId: string) => `${API_BASE_URL}/groups/${groupId}/leave`,
  },
  PROJECT: {
    ALL: `${API_BASE_URL}/projects`,
    BY_ID: (projectId: string) => `${API_BASE_URL}/projects/${projectId}`,
    SUPERVISOR_IDEAS: `${API_BASE_URL}/projects/supervisor/ideas`,
    SELECT_IDEA: `${API_BASE_URL}/projects/select-idea`,
    REQUEST_CUSTOM_IDEA: `${API_BASE_URL}/projects/request-custom-idea`,
    MY_PROJECT: `${API_BASE_URL}/projects/my-project`,
    SUBMIT_GITHUB: `${API_BASE_URL}/projects/github`,
    MY_GITHUB: `${API_BASE_URL}/projects/github/my`,
  },
  PROPOSAL: {
    UPLOAD: `${API_BASE_URL}/proposals`,
    SUBMIT: (id: string) => `${API_BASE_URL}/proposals/${id}/submit`,
    MY_DOCUMENTS: `${API_BASE_URL}/documents/my-documents`,
  },
  DOCUMENTS: {
    UPLOAD: `${API_BASE_URL}/documents`,
    MY_DOCUMENTS: `${API_BASE_URL}/documents/my-documents`,
  },
  PANELS: {
    ALL: `${API_BASE_URL}/panels`,
    BY_ID: (id: string) => `${API_BASE_URL}/panels/${id}`,
  },
  SCHEDULES: {
    ALL: `${API_BASE_URL}/schedules`,
    BY_ID: (id: string) => `${API_BASE_URL}/schedules/${id}`,
    AUTO_SCHEDULE: `${API_BASE_URL}/schedules/auto-schedule`,
    SWAP: `${API_BASE_URL}/schedules/swap`,
    MY_SCHEDULE: `${API_BASE_URL}/students/schedule/my-schedule`,
    MY_PANEL: `${API_BASE_URL}/students/schedule/my-panel`,
  },
} as const;
